# Numpy Built-in Functions

In [1]:
import numpy as np

In [41]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
#np.linspace
np.linspace(10,100,10)

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [40]:
np.random.randint(5,10,10)

array([9, 5, 5, 6, 6, 8, 7, 6, 8, 9])

In [37]:
#np.reshape
A = np.random.randint(15,size=(4,3))
A

array([[10,  4,  7],
       [ 9,  3, 14],
       [ 5,  8,  3],
       [ 1,  3, 10]])

In [38]:
A.reshape(3,4)
A

array([[10,  4,  7],
       [ 9,  3, 14],
       [ 5,  8,  3],
       [ 1,  3, 10]])

In [30]:
#np.log
np.logspace(0,10,5,base=2)

array([1.00000000e+00, 5.65685425e+00, 3.20000000e+01, 1.81019336e+02,
       1.02400000e+03])

In [42]:
#np.transpose
x = np.arange(4).reshape((2,2))
x

array([[0, 1],
       [2, 3]])

In [43]:
np.transpose(x)

array([[0, 2],
       [1, 3]])

In [25]:
#np.array
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [31]:
#np.zeros
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [33]:
#np.ones
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [35]:
#np.full
np.full((2,4),fill_value=4)

array([[4, 4, 4, 4],
       [4, 4, 4, 4]])

In [39]:
#np,.sort
arr = np.array([2,3,1,7,4,5])
np.sort(arr)

array([1, 2, 3, 4, 5, 7])

In [29]:
#np.random.random
np.random.random(3)

array([0.9855568 , 0.05431563, 0.0140175 ])

In [44]:
#np.empty
np.empty([2, 2])

array([[1., 1.],
       [1., 1.]])

In [27]:
#np.arange
np.arange(5,10,2)

array([5, 7, 9])

In [45]:
np.max(arr)

7

In [46]:
np.mean(arr,dtype='int')

3

In [47]:
arr = np.array([[1,2,3],[5,8,4]])
np.median(arr)

3.5

In [48]:
arr = np.array([[ 8],[14],[ 1],[ 8],[11],[ 4],[ 9],[ 4],[ 1],[13],[13],[11]])
np.squeeze(arr)

array([ 8, 14,  1,  8, 11,  4,  9,  4,  1, 13, 13, 11])

In [49]:
a = np.array([0,0,1,1,1,0])
np.count_nonzero(a)

3

In [28]:
np.random.randint(5,10,10)

array([6, 9, 8, 9, 8, 7, 7, 8, 9, 6])

# Pandas Built in Functions

In [50]:
import pandas as pd

In [54]:
df = pd.read_csv(r"C:\Users\Baliqees\Desktop\cars.csv")
df

VehicleID Location          Maker                 Model   Year  Colour  \
0     VHL12546    Abuja          Honda   Accord Coupe EX V-6  2,011  Silver   
1     VHL18827   Ibadan        Hyundai                Sonata  2,012  Silver   
2     VHL19499    Lagos          Lexus                RX 350  2,010     Red   
3     VHL17991    Abuja  Mercedes-Benz             GLE-Class  2,017    Blue   
4     VHL12170   Ibadan         Toyota            Highlander  2,002     Red   
...        ...      ...            ...                   ...    ...     ...   
7200  VHL14329    Abuja          Honda                 Civic  2,018    Gray   
7201  VHL10637    Abuja            BMW                    X3  2,007   White   
7202  VHL19734    Abuja         Toyota  RAV4 2.5 Limited 4x4  2,010   Black   
7203  VHL15569    Lagos  Mercedes-Benz         GLK-Class 350  2,012   Black   
7204  VHL15246    Abuja          Honda      Accord Crosstour  2,012    Gray   

      Amount (Million Naira)           Type Distance  
0                       2.20  Nigerian Used      NaN  
1                       3.50  Nigerian Used  125,000  
2                       9.20   Foreign Used  110,852  
3                      22.80   Foreign Used   30,000  
4                       2.60  Nigerian Used  125,206  
...                      ...            ...      ...  
7200                    5.70   Foreign Used   65,000  
7201                    4.00  Nigerian Used  200,000  
7202                    2.85  Nigerian Used      NaN  
7203                    8.65   Foreign Used   85,750  
7204                    3.38  Nigerian Used   83,308  

[7205 rows x 9 columns]

In [57]:
df.head()

VehicleID Location          Maker                Model   Year  Colour  \
0  VHL12546    Abuja          Honda  Accord Coupe EX V-6  2,011  Silver   
1  VHL18827   Ibadan        Hyundai               Sonata  2,012  Silver   
2  VHL19499    Lagos          Lexus               RX 350  2,010     Red   
3  VHL17991    Abuja  Mercedes-Benz            GLE-Class  2,017    Blue   
4  VHL12170   Ibadan         Toyota           Highlander  2,002     Red   

   Amount (Million Naira)           Type Distance  
0                     2.2  Nigerian Used      NaN  
1                     3.5  Nigerian Used  125,000  
2                     9.2   Foreign Used  110,852  
3                    22.8   Foreign Used   30,000  
4                     2.6  Nigerian Used  125,206

In [63]:
df.columns

Index(['VehicleID', 'Maker', 'Model', 'Colour', 'Amount (Million Naira)',
       'Type', 'Distance'],
      dtype='object')

In [68]:
df = df.drop(columns=['Model','Colour'])

In [69]:
df

VehicleID          Maker  Amount (Million Naira)           Type Distance
0     VHL12546          Honda                    2.20  Nigerian Used      NaN
1     VHL18827        Hyundai                    3.50  Nigerian Used  125,000
2     VHL19499          Lexus                    9.20   Foreign Used  110,852
3     VHL17991  Mercedes-Benz                   22.80   Foreign Used   30,000
4     VHL12170         Toyota                    2.60  Nigerian Used  125,206
...        ...            ...                     ...            ...      ...
7200  VHL14329          Honda                    5.70   Foreign Used   65,000
7201  VHL10637            BMW                    4.00  Nigerian Used  200,000
7202  VHL19734         Toyota                    2.85  Nigerian Used      NaN
7203  VHL15569  Mercedes-Benz                    8.65   Foreign Used   85,750
7204  VHL15246          Honda                    3.38  Nigerian Used   83,308

[7205 rows x 5 columns]

In [70]:
len(df)

7205

In [74]:
df.dtypes

VehicleID                  object
Maker                      object
Amount (Million Naira)    float64
Type                       object
Distance                   object
dtype: object

In [75]:
df.select_dtypes(include='int64')

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[7205 rows x 0 columns]

In [76]:
df.select_dtypes(exclude='int64')

VehicleID          Maker  Amount (Million Naira)           Type Distance
0     VHL12546          Honda                    2.20  Nigerian Used      NaN
1     VHL18827        Hyundai                    3.50  Nigerian Used  125,000
2     VHL19499          Lexus                    9.20   Foreign Used  110,852
3     VHL17991  Mercedes-Benz                   22.80   Foreign Used   30,000
4     VHL12170         Toyota                    2.60  Nigerian Used  125,206
...        ...            ...                     ...            ...      ...
7200  VHL14329          Honda                    5.70   Foreign Used   65,000
7201  VHL10637            BMW                    4.00  Nigerian Used  200,000
7202  VHL19734         Toyota                    2.85  Nigerian Used      NaN
7203  VHL15569  Mercedes-Benz                    8.65   Foreign Used   85,750
7204  VHL15246          Honda                    3.38  Nigerian Used   83,308

[7205 rows x 5 columns]

In [77]:
df.sample(n = 200)

VehicleID          Maker  Amount (Million Naira)           Type Distance
4136  VHL14942  Mercedes-Benz                   12.90   Foreign Used      NaN
7086  VHL19131          Lexus                   12.80   Foreign Used      NaN
5989  VHL12089          Lexus                    5.00   Foreign Used  165,656
901   VHL17194          Lexus                    4.75   Foreign Used   86,000
5055  VHL14021         Toyota                   26.00      Brand New      NaN
...        ...            ...                     ...            ...      ...
4797  VHL11520         Toyota                    2.50  Nigerian Used   80,000
2450  VHL13295          Lexus                    4.10   Foreign Used   72,311
2592  VHL14189          Lexus                    3.00  Nigerian Used  102,000
5102  VHL13929          Honda                    6.80   Foreign Used      NaN
45    VHL18868  Mercedes-Benz                    3.50  Nigerian Used  120,213

[200 rows x 5 columns]

In [78]:
df.sample(frac = 0.25)

VehicleID          Maker  Amount (Million Naira)          Type Distance
6621  VHL15993          Lexus                    4.00  Foreign Used   99,809
3110  VHL19354            BMW                    6.00  Foreign Used   50,000
1168  VHL19149         Toyota                    4.49           NaN  275,053
521   VHL13837         Toyota                   15.00  Foreign Used   30,000
1354  VHL19203         Toyota                    8.85  Foreign Used  105,867
...        ...            ...                     ...           ...      ...
1893  VHL14271         Toyota                    3.00  Foreign Used   75,000
6355  VHL17356          Lexus                   25.00  Foreign Used   36,000
3508  VHL19971  Mercedes-Benz                    5.61           NaN  173,113
5158  VHL10192          Lexus                   23.85  Foreign Used      NaN
5565  VHL19074         Toyota                    3.60  Foreign Used   97,621

[1801 rows x 5 columns]

In [79]:
df['Amount (Million Naira)'].where(df['Amount (Million Naira)'] > 8.85)

0        NaN
1        NaN
2        9.2
3       22.8
4        NaN
        ... 
7200     NaN
7201     NaN
7202     NaN
7203     NaN
7204     NaN
Name: Amount (Million Naira), Length: 7205, dtype: float64

In [82]:
df.VehicleID.unique()

array(['VHL12546', 'VHL18827', 'VHL19499', ..., 'VHL12205', 'VHL17562',
       'VHL15246'], dtype=object)

In [83]:
df.Maker.nunique()

55

In [84]:
df.nunique()

VehicleID                 5141
Maker                       55
Amount (Million Naira)     742
Type                         3
Distance                  3144
dtype: int64

In [86]:
df.rename(columns = {"Amount (Million Naira)": "Price (Million)", "Type": "Used or Not"})

VehicleID          Maker  Price (Million)    Used or Not Distance
0     VHL12546          Honda             2.20  Nigerian Used      NaN
1     VHL18827        Hyundai             3.50  Nigerian Used  125,000
2     VHL19499          Lexus             9.20   Foreign Used  110,852
3     VHL17991  Mercedes-Benz            22.80   Foreign Used   30,000
4     VHL12170         Toyota             2.60  Nigerian Used  125,206
...        ...            ...              ...            ...      ...
7200  VHL14329          Honda             5.70   Foreign Used   65,000
7201  VHL10637            BMW             4.00  Nigerian Used  200,000
7202  VHL19734         Toyota             2.85  Nigerian Used      NaN
7203  VHL15569  Mercedes-Benz             8.65   Foreign Used   85,750
7204  VHL15246          Honda             3.38  Nigerian Used   83,308

[7205 rows x 5 columns]

In [87]:
df['Distance'].fillna(0, inplace=True)

In [88]:
df

VehicleID          Maker  Amount (Million Naira)           Type Distance
0     VHL12546          Honda                    2.20  Nigerian Used        0
1     VHL18827        Hyundai                    3.50  Nigerian Used  125,000
2     VHL19499          Lexus                    9.20   Foreign Used  110,852
3     VHL17991  Mercedes-Benz                   22.80   Foreign Used   30,000
4     VHL12170         Toyota                    2.60  Nigerian Used  125,206
...        ...            ...                     ...            ...      ...
7200  VHL14329          Honda                    5.70   Foreign Used   65,000
7201  VHL10637            BMW                    4.00  Nigerian Used  200,000
7202  VHL19734         Toyota                    2.85  Nigerian Used        0
7203  VHL15569  Mercedes-Benz                    8.65   Foreign Used   85,750
7204  VHL15246          Honda                    3.38  Nigerian Used   83,308

[7205 rows x 5 columns]

In [89]:
df.count(0)

VehicleID                 7205
Maker                     7205
Amount (Million Naira)    7188
Type                      7008
Distance                  7205
dtype: int64

In [90]:
df.count(1)

0       5
1       5
2       5
3       5
4       5
       ..
7200    5
7201    5
7202    5
7203    5
7204    5
Length: 7205, dtype: int64

In [91]:
df['Distance'].value_counts()

0          2360
75,000       70
65,000       54
85,000       53
100,000      53
           ... 
10,559        1
56,443        1
86,582        1
175,294       1
83,308        1
Name: Distance, Length: 3145, dtype: int64

In [92]:
df.describe()

Amount (Million Naira)
count             7188.000000
mean                11.847999
std                 25.318922
min                  0.450000
25%                  3.500000
50%                  5.650000
75%                 11.662500
max                456.000000